version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    container_name: simulator
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
    - ./services/simulator/config/config.json:/config/config.json
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - WRITER_PORT=8081
      - WRITER_HOST=writer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROMETHEUS_METRICS_PORT=8082
    ports:
      - "8082:8082"

  writer:
    build:
      context: .
      dockerfile: Dockerfile.writer
    container_name: writer
    ports:
      - "8081:8081"
      - "8001:8001"
    environment:
      - PORT=8081
    volumes:
      - ./logs:/logs

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
